### ISSUE TITLE
measurable learning objectives, Bloom's taxonomy

### ISSUE THREAD

**Issue by anacost** [carpentries/curriculum-development#19]
in section 1.5 The structure of our curriculum (https://github.com/carpentries/curriculum-development/blob/master/01-conceptual-elements.Rmd) in 1.5.1.1 Episodes, you mention
"It lists measurable learning objectives related to those concepts and contains a number of challenges to assess learners’ ability to perform those learning objectives. "
This sentence summarises the most important in the learning objectives: measurable learning objectives. 

It is important to mention https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/
explicitly since it guides how we should write learning objectives. In practice, we contact Kari Jordan to verify the lessons' learning objectives. 

It would be good to explain what kind of verbs we should use. 
What do you think about it?

**Comment by anacost** [comment]
The best guidance about learning objectives is probably in "Appendix D - What are Learning Objectives and How can We Use Them?" from the book "Ambrose, Bridges, Lovett, DiPietro, Norman, How Learning Works".
Could we use this appendix D?

**Comment by ErinBecker** [comment]
Thank you @anacost! These are great suggestions and good resources to have. I was trying to steer away from using Bloom's Taxonomy as a prescriptive tool (e.g. "you should be writing learning objectives at XYZ levels of the pyramid") and use it more as a descriptive tool (e.g. "these are action words that indicate different levels of thought"). People may be using these materials (in future) to develop lessons at a wide variety of levels, from complete novice to intermediate or specialized expert learners. I'd like to avoid saying that they "should" make their learning objectives at a particular level, because it should really depend on their target audience. 

In the past, we have asked @kariljordan to review learning objectives for many lessons, but with the rapid growth of lessons (including lessons developed for use outside of official The Carpentries spaces) that isn't a scalable strategy, so it will be useful to give guidance on how to evaluate learning objectives independently.

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues. I hope this issue has largely been addressed with the [Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/).
